name: raw
version: 0.2.1
author: terrier989 <terrier989@gmail.com>
homepage: https://github.com/terrier989/dart-raw
description: A package for writing, reading, and debugging binary data.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  fixnum: ^1.0.0
  matcher: ^0.12.10
  meta: ^1.3.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  test: ^1.16.8